/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author pinku
 */
public class CorreoExiste extends javax.swing.JPanel {

    /**
     * Creates new form CorreoExiste
     */
    public CorreoExiste() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBCorreoExise = new javax.swing.JLabel();

        setBackground(new java.awt.Color(2, 0, 8));

        LBCorreoExise.setBackground(new java.awt.Color(2, 0, 8));
        LBCorreoExise.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        LBCorreoExise.setForeground(new java.awt.Color(153, 0, 0));
        LBCorreoExise.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBCorreoExise.setText("Este correo ya está registrado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LBCorreoExise, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LBCorreoExise, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBCorreoExise;
    // End of variables declaration//GEN-END:variables
}
