package Vista;

import Modelo.Conexion;
import Controlador.Operaciones;
import java.awt.BorderLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author KevinJp
 */
public class Login extends javax.swing.JFrame {

    DatoErroneo de = new DatoErroneo();
    /**
     * Creates new form InicioLogin
     *
     */
    Conexion cx = new Conexion();

    int LayoutX;
    int LayoutY;

    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPDashboard = new javax.swing.JPanel();
        JPInicioSesion = new javax.swing.JPanel();
        TXTLogin = new javax.swing.JLabel();
        LBCorreo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TXTCorreo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        LBCorreo1 = new javax.swing.JLabel();
        TXTContraseña = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        LBCorreo2 = new javax.swing.JLabel();
        BTNResetPass = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        BTNLogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BTNRegistrarse = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        JPErrorDatos = new javax.swing.JPanel();
        JPEnc = new javax.swing.JPanel();
        BTNMinizise = new javax.swing.JButton();
        BTNClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        LBIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        JPDashboard.setBackground(new java.awt.Color(2, 0, 8));
        JPDashboard.setPreferredSize(new java.awt.Dimension(1020, 650));

        JPInicioSesion.setBackground(new java.awt.Color(2, 0, 8));
        JPInicioSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        TXTLogin.setBackground(new java.awt.Color(4, 0, 14));
        TXTLogin.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        TXTLogin.setForeground(new java.awt.Color(255, 255, 255));
        TXTLogin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TXTLogin.setText("Iniciar sesión");
        TXTLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        LBCorreo.setBackground(new java.awt.Color(4, 0, 14));
        LBCorreo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        LBCorreo.setForeground(new java.awt.Color(255, 255, 255));
        LBCorreo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBCorreo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/huella-de-carbono.png"))); // NOI18N

        TXTCorreo.setBackground(new java.awt.Color(2, 0, 8));
        TXTCorreo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        TXTCorreo.setForeground(new java.awt.Color(255, 255, 255));
        TXTCorreo.setToolTipText("");
        TXTCorreo.setBorder(null);
        TXTCorreo.setCaretColor(new java.awt.Color(255, 255, 255));
        TXTCorreo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TXTCorreo.setDragEnabled(true);
        TXTCorreo.setOpaque(true);
        TXTCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TXTCorreoMouseClicked(evt);
            }
        });
        TXTCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTCorreoActionPerformed(evt);
            }
        });
        TXTCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TXTCorreoKeyPressed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        LBCorreo1.setBackground(new java.awt.Color(4, 0, 14));
        LBCorreo1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        LBCorreo1.setForeground(new java.awt.Color(255, 255, 255));
        LBCorreo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBCorreo1.setText("Correo");
        LBCorreo1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        TXTContraseña.setBackground(new java.awt.Color(2, 0, 8));
        TXTContraseña.setForeground(new java.awt.Color(255, 255, 255));
        TXTContraseña.setBorder(null);
        TXTContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TXTContraseñaMouseClicked(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        LBCorreo2.setBackground(new java.awt.Color(4, 0, 14));
        LBCorreo2.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        LBCorreo2.setForeground(new java.awt.Color(255, 255, 255));
        LBCorreo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBCorreo2.setText("Contraseña");
        LBCorreo2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        BTNResetPass.setBackground(new java.awt.Color(2, 0, 8));
        BTNResetPass.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        BTNResetPass.setForeground(new java.awt.Color(255, 255, 255));
        BTNResetPass.setText("¿Olvidaste tu contraseña?");
        BTNResetPass.setBorder(null);
        BTNResetPass.setBorderPainted(false);
        BTNResetPass.setContentAreaFilled(false);
        BTNResetPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTNResetPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNResetPassActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        BTNLogin.setBackground(new java.awt.Color(2, 0, 8));
        BTNLogin.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        BTNLogin.setForeground(new java.awt.Color(255, 255, 255));
        BTNLogin.setText("Iniciar sesión");
        BTNLogin.setBorder(null);
        BTNLogin.setBorderPainted(false);
        BTNLogin.setContentAreaFilled(false);
        BTNLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTNLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNLoginActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("¿No tienes cuenta?");

        BTNRegistrarse.setBackground(new java.awt.Color(2, 0, 8));
        BTNRegistrarse.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        BTNRegistrarse.setForeground(new java.awt.Color(255, 255, 255));
        BTNRegistrarse.setText("Registrate aquí");
        BTNRegistrarse.setBorder(null);
        BTNRegistrarse.setBorderPainted(false);
        BTNRegistrarse.setContentAreaFilled(false);
        BTNRegistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTNRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNRegistrarseActionPerformed(evt);
            }
        });

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));

        JPErrorDatos.setBackground(new java.awt.Color(2, 0, 8));

        javax.swing.GroupLayout JPErrorDatosLayout = new javax.swing.GroupLayout(JPErrorDatos);
        JPErrorDatos.setLayout(JPErrorDatosLayout);
        JPErrorDatosLayout.setHorizontalGroup(
            JPErrorDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 295, Short.MAX_VALUE)
        );
        JPErrorDatosLayout.setVerticalGroup(
            JPErrorDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout JPInicioSesionLayout = new javax.swing.GroupLayout(JPInicioSesion);
        JPInicioSesion.setLayout(JPInicioSesionLayout);
        JPInicioSesionLayout.setHorizontalGroup(
            JPInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPInicioSesionLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(JPInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JPInicioSesionLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGroup(JPInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(JPInicioSesionLayout.createSequentialGroup()
                                    .addGap(114, 114, 114)
                                    .addComponent(TXTLogin)
                                    .addGap(39, 39, 39))
                                .addGroup(JPInicioSesionLayout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(JPInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LBCorreo2)
                                        .addGroup(JPInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(JPInicioSesionLayout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(JPInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(BTNRegistrarse)
                                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(188, 188, 188))
                                            .addComponent(LBCorreo1))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPInicioSesionLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(JPInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TXTContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                                            .addComponent(jSeparator2))
                                        .addComponent(TXTCorreo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(JPInicioSesionLayout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPInicioSesionLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JPErrorDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(JPInicioSesionLayout.createSequentialGroup()
                        .addComponent(LBCorreo)
                        .addGap(59, 59, 59)
                        .addGroup(JPInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator3)
                            .addComponent(BTNResetPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTNLogin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(54, 54, 54)))
                .addContainerGap(442, Short.MAX_VALUE))
        );
        JPInicioSesionLayout.setVerticalGroup(
            JPInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPInicioSesionLayout.createSequentialGroup()
                .addGroup(JPInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPInicioSesionLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(TXTLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JPErrorDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LBCorreo1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(TXTCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(LBCorreo2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXTContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPInicioSesionLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel4)))
                .addGap(0, 0, 0)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JPInicioSesionLayout.createSequentialGroup()
                        .addComponent(BTNResetPass)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addComponent(BTNLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(JPInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(BTNRegistrarse))
                .addGap(0, 0, 0)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout JPDashboardLayout = new javax.swing.GroupLayout(JPDashboard);
        JPDashboard.setLayout(JPDashboardLayout);
        JPDashboardLayout.setHorizontalGroup(
            JPDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPInicioSesion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JPDashboardLayout.setVerticalGroup(
            JPDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPDashboardLayout.createSequentialGroup()
                .addComponent(JPInicioSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        JPEnc.setBackground(new java.awt.Color(2, 0, 8));
        JPEnc.setPreferredSize(new java.awt.Dimension(1020, 40));
        JPEnc.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                JPEncMouseDragged(evt);
            }
        });
        JPEnc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPEncMousePressed(evt);
            }
        });

        BTNMinizise.setBackground(new java.awt.Color(2, 0, 8));
        BTNMinizise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minimize.png"))); // NOI18N
        BTNMinizise.setBorder(null);
        BTNMinizise.setBorderPainted(false);
        BTNMinizise.setContentAreaFilled(false);
        BTNMinizise.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTNMinizise.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BTNMinizise.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BTNMinizise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTNMiniziseMouseClicked(evt);
            }
        });
        BTNMinizise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNMiniziseActionPerformed(evt);
            }
        });

        BTNClose.setBackground(new java.awt.Color(2, 0, 8));
        BTNClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/close.png"))); // NOI18N
        BTNClose.setBorder(null);
        BTNClose.setBorderPainted(false);
        BTNClose.setContentAreaFilled(false);
        BTNClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTNClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTNCloseMouseClicked(evt);
            }
        });
        BTNClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCloseActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("EcoCal");

        LBIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/huella-de-carbono icon.png"))); // NOI18N

        javax.swing.GroupLayout JPEncLayout = new javax.swing.GroupLayout(JPEnc);
        JPEnc.setLayout(JPEncLayout);
        JPEncLayout.setHorizontalGroup(
            JPEncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPEncLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LBIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTNMinizise, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BTNClose, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        JPEncLayout.setVerticalGroup(
            JPEncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LBIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JPEncLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPEncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNClose, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNMinizise, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPEnc, javax.swing.GroupLayout.DEFAULT_SIZE, 1119, Short.MAX_VALUE)
            .addComponent(JPDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 1119, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(JPEnc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(JPDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTNMiniziseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNMiniziseMouseClicked
        if (evt.getButton() == java.awt.event.MouseEvent.BUTTON1) {
            this.setExtendedState(ICONIFIED);
        }
    }//GEN-LAST:event_BTNMiniziseMouseClicked

    private void BTNMiniziseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNMiniziseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNMiniziseActionPerformed

    private void BTNCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNCloseMouseClicked
        if (evt.getButton() == java.awt.event.MouseEvent.BUTTON1) {
            System.exit(0);
        }
    }//GEN-LAST:event_BTNCloseMouseClicked

    private void BTNCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCloseActionPerformed

    }//GEN-LAST:event_BTNCloseActionPerformed

    private void JPEncMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPEncMouseDragged
        this.setLocation(evt.getXOnScreen() - LayoutX, evt.getYOnScreen() - LayoutY);
    }//GEN-LAST:event_JPEncMouseDragged

    private void JPEncMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPEncMousePressed
        if (evt.getButton() == java.awt.event.MouseEvent.BUTTON1) {
            LayoutX = evt.getX();
            LayoutY = evt.getY();/*Obtiene la posicion x,y*/
        }
    }//GEN-LAST:event_JPEncMousePressed

    private void TXTCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTCorreoActionPerformed

    private void BTNResetPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNResetPassActionPerformed
        ResetPass rp = new ResetPass();
        rp.setVisible(true);
    }//GEN-LAST:event_BTNResetPassActionPerformed

    private void BTNLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNLoginActionPerformed
        try {
            Operaciones validaciones = new Operaciones();
            String correo = TXTCorreo.getText();
            String contraseña = String.valueOf(TXTContraseña.getPassword());
            String query = "SELECT concat(Nombre,' ',Apellido) as Usuario,Correo,Contraseña FROM usuarios WHERE Correo='" + correo + "'and Contraseña='" + contraseña + "'";
            Statement st = cx.conectar().createStatement();
            ResultSet rs = st.executeQuery(query);
            if (rs.next()) {
                MenuPrincipal mp = new MenuPrincipal();
                mp.TXTNomUsu.setText(rs.getString("Usuario"));
               
                mp.setVisible(true);
                this.dispose();

            } else {
                
                de.setSize(295, 100);
                de.setLocation(0, 0);

                JPErrorDatos.removeAll();
                JPErrorDatos.add(de, BorderLayout.CENTER);
                JPErrorDatos.revalidate();
                JPErrorDatos.repaint();
                de.setVisible(true);
            }

        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_BTNLoginActionPerformed

    private void BTNRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNRegistrarseActionPerformed
        Registro rg = new Registro();
        rg.setVisible(true);
        this.dispose();
        
        
        
    }//GEN-LAST:event_BTNRegistrarseActionPerformed

    private void TXTCorreoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTCorreoKeyPressed

    }//GEN-LAST:event_TXTCorreoKeyPressed

    private void TXTCorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTCorreoMouseClicked

            de.setVisible(false);
    }//GEN-LAST:event_TXTCorreoMouseClicked

    private void TXTContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTContraseñaMouseClicked
        de.setVisible(false);
    }//GEN-LAST:event_TXTContraseñaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNClose;
    private javax.swing.JButton BTNLogin;
    private javax.swing.JButton BTNMinizise;
    private javax.swing.JButton BTNRegistrarse;
    private javax.swing.JButton BTNResetPass;
    private javax.swing.JPanel JPDashboard;
    private javax.swing.JPanel JPEnc;
    private javax.swing.JPanel JPErrorDatos;
    private javax.swing.JPanel JPInicioSesion;
    private javax.swing.JLabel LBCorreo;
    private javax.swing.JLabel LBCorreo1;
    private javax.swing.JLabel LBCorreo2;
    private javax.swing.JLabel LBIcon;
    private javax.swing.JPasswordField TXTContraseña;
    private javax.swing.JTextField TXTCorreo;
    private javax.swing.JLabel TXTLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
