package Vista;

import Modelo.Conexion;
import Modelo.SQLUsuarios;
import Modelo.Usuarios;
import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author KevinJp
 */
public class MenuPrincipal extends javax.swing.JFrame {

    Login lg = new Login();
    /**
     * Creates new form MenuPrincipal
     */
    int LayoutX;
    int LayoutY;
    SQLUsuarios sqlus = new SQLUsuarios();
    Usuarios usr = new Usuarios();

    public MenuPrincipal() {
        initComponents();
        //MostrarUsuario();

        Inicio in = new Inicio();
        in.setSize(720, 670);
        in.setLocation(0, 0);

        JPDashboard.removeAll();
        JPDashboard.add(in, BorderLayout.CENTER);
        JPDashboard.revalidate();
        JPDashboard.repaint();

    }

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPDashboard = new javax.swing.JPanel();
        JPBar = new javax.swing.JPanel();
        TXTNomUsu = new javax.swing.JLabel();
        BTNCerrarrSesion = new javax.swing.JButton();
        TXTImgUsu = new javax.swing.JLabel();
        BTNInicio = new javax.swing.JButton();
        LBImgInicio = new javax.swing.JLabel();
        BTNPreguntas = new javax.swing.JButton();
        LBImgAbout = new javax.swing.JLabel();
        BTNAbout = new javax.swing.JButton();
        LBImgPregunta1 = new javax.swing.JLabel();
        BTNRanking1 = new javax.swing.JButton();
        LBImTop1 = new javax.swing.JLabel();
        LBImgLogOut = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        JPEnc = new javax.swing.JPanel();
        BTNMinizise = new javax.swing.JButton();
        BTNClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        LBIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EcoCal");
        setBackground(new java.awt.Color(2, 0, 8));
        setName("MP0"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPDashboard.setBackground(new java.awt.Color(2, 0, 8));
        JPDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout JPDashboardLayout = new javax.swing.GroupLayout(JPDashboard);
        JPDashboard.setLayout(JPDashboardLayout);
        JPDashboardLayout.setHorizontalGroup(
            JPDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        JPDashboardLayout.setVerticalGroup(
            JPDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        getContentPane().add(JPDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 720, 670));
        JPDashboard.getAccessibleContext().setAccessibleName("Dashboard");

        JPBar.setBackground(new java.awt.Color(2, 0, 8));
        JPBar.setName(""); // NOI18N

        TXTNomUsu.setBackground(new java.awt.Color(4, 0, 14));
        TXTNomUsu.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        TXTNomUsu.setForeground(new java.awt.Color(204, 204, 204));
        TXTNomUsu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        BTNCerrarrSesion.setBackground(new java.awt.Color(4, 0, 14));
        BTNCerrarrSesion.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        BTNCerrarrSesion.setForeground(new java.awt.Color(204, 204, 204));
        BTNCerrarrSesion.setText("Sign out");
        BTNCerrarrSesion.setBorder(null);
        BTNCerrarrSesion.setBorderPainted(false);
        BTNCerrarrSesion.setContentAreaFilled(false);
        BTNCerrarrSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTNCerrarrSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCerrarrSesionActionPerformed(evt);
            }
        });

        TXTImgUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user b.png"))); // NOI18N

        BTNInicio.setBackground(new java.awt.Color(5, 0, 19));
        BTNInicio.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        BTNInicio.setForeground(new java.awt.Color(204, 204, 204));
        BTNInicio.setText("Inicio");
        BTNInicio.setBorder(null);
        BTNInicio.setBorderPainted(false);
        BTNInicio.setContentAreaFilled(false);
        BTNInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTNInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNInicioActionPerformed(evt);
            }
        });

        LBImgInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pagina-de-inicio.png"))); // NOI18N

        BTNPreguntas.setBackground(new java.awt.Color(5, 0, 19));
        BTNPreguntas.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        BTNPreguntas.setForeground(new java.awt.Color(204, 204, 204));
        BTNPreguntas.setText("Preguntas");
        BTNPreguntas.setBorder(null);
        BTNPreguntas.setBorderPainted(false);
        BTNPreguntas.setContentAreaFilled(false);
        BTNPreguntas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTNPreguntas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNPreguntasActionPerformed(evt);
            }
        });

        LBImgAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/informacion.png"))); // NOI18N

        BTNAbout.setBackground(new java.awt.Color(5, 0, 19));
        BTNAbout.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        BTNAbout.setForeground(new java.awt.Color(204, 204, 204));
        BTNAbout.setText("Acerca de");
        BTNAbout.setBorder(null);
        BTNAbout.setBorderPainted(false);
        BTNAbout.setContentAreaFilled(false);
        BTNAbout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTNAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAboutActionPerformed(evt);
            }
        });

        LBImgPregunta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/checklist.png"))); // NOI18N

        BTNRanking1.setBackground(new java.awt.Color(5, 0, 19));
        BTNRanking1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        BTNRanking1.setForeground(new java.awt.Color(204, 204, 204));
        BTNRanking1.setText("Ranking");
        BTNRanking1.setBorder(null);
        BTNRanking1.setBorderPainted(false);
        BTNRanking1.setContentAreaFilled(false);
        BTNRanking1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTNRanking1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNRanking1ActionPerformed(evt);
            }
        });

        LBImTop1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/trophy.png"))); // NOI18N

        LBImgLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logout.png"))); // NOI18N

        javax.swing.GroupLayout JPBarLayout = new javax.swing.GroupLayout(JPBar);
        JPBar.setLayout(JPBarLayout);
        JPBarLayout.setHorizontalGroup(
            JPBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPBarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(TXTImgUsu)
                .addGap(18, 18, 18)
                .addComponent(TXTNomUsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(JPBarLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(JPBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LBImgLogOut)
                    .addComponent(LBImgInicio)
                    .addComponent(LBImgAbout)
                    .addComponent(LBImgPregunta1)
                    .addComponent(LBImTop1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BTNAbout, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(BTNPreguntas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNRanking1, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(BTNInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNCerrarrSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        JPBarLayout.setVerticalGroup(
            JPBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPBarLayout.createSequentialGroup()
                .addGroup(JPBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPBarLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(TXTImgUsu))
                    .addGroup(JPBarLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(TXTNomUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68)
                .addGroup(JPBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBImgInicio))
                .addGap(50, 50, 50)
                .addGroup(JPBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBImgPregunta1)
                    .addComponent(BTNPreguntas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(JPBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBImTop1)
                    .addComponent(BTNRanking1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(JPBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBImgAbout)
                    .addComponent(BTNAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(JPBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BTNCerrarrSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBImgLogOut))
                .addContainerGap())
        );

        getContentPane().add(JPBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 670));
        JPBar.getAccessibleContext().setAccessibleName("Barra");
        JPBar.getAccessibleContext().setAccessibleDescription("");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, -1));

        JPEnc.setBackground(new java.awt.Color(2, 0, 8));
        JPEnc.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                JPEncMouseDragged(evt);
            }
        });
        JPEnc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPEncMousePressed(evt);
            }
        });

        BTNMinizise.setBackground(new java.awt.Color(2, 0, 8));
        BTNMinizise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minimize.png"))); // NOI18N
        BTNMinizise.setBorder(null);
        BTNMinizise.setBorderPainted(false);
        BTNMinizise.setContentAreaFilled(false);
        BTNMinizise.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTNMinizise.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BTNMinizise.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BTNMinizise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTNMiniziseMouseClicked(evt);
            }
        });
        BTNMinizise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNMiniziseActionPerformed(evt);
            }
        });

        BTNClose.setBackground(new java.awt.Color(2, 0, 8));
        BTNClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/close.png"))); // NOI18N
        BTNClose.setBorder(null);
        BTNClose.setBorderPainted(false);
        BTNClose.setContentAreaFilled(false);
        BTNClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTNClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTNCloseMouseClicked(evt);
            }
        });
        BTNClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCloseActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("EcoCal");

        LBIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/huella-de-carbono icon.png"))); // NOI18N

        javax.swing.GroupLayout JPEncLayout = new javax.swing.GroupLayout(JPEnc);
        JPEnc.setLayout(JPEncLayout);
        JPEncLayout.setHorizontalGroup(
            JPEncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPEncLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LBIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(797, 797, 797)
                .addComponent(BTNMinizise, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BTNClose, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        JPEncLayout.setVerticalGroup(
            JPEncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LBIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JPEncLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPEncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNClose, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNMinizise, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(JPEnc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 40));

        getAccessibleContext().setAccessibleName("MP0");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTNInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNInicioActionPerformed
        Inicio in = new Inicio();
        in.setSize(720, 670);
        in.setLocation(0, 0);

        JPDashboard.removeAll();
        JPDashboard.add(in, BorderLayout.CENTER);
        JPDashboard.revalidate();
        JPDashboard.repaint();
    }//GEN-LAST:event_BTNInicioActionPerformed

    private void BTNPreguntasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNPreguntasActionPerformed
        Preguntas pre = new Preguntas();
        pre.setSize(720, 670);
        pre.setLocation(0, 0);

        JPDashboard.removeAll();
        JPDashboard.add(pre, BorderLayout.CENTER);
        JPDashboard.revalidate();
        JPDashboard.repaint();
    }//GEN-LAST:event_BTNPreguntasActionPerformed

    private void BTNAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAboutActionPerformed
        About ab = new About();
        ab.setSize(720, 670);
        ab.setLocation(0, 0);

        JPDashboard.removeAll();
        JPDashboard.add(ab, BorderLayout.CENTER);
        JPDashboard.revalidate();
        JPDashboard.repaint();
    }//GEN-LAST:event_BTNAboutActionPerformed

    private void BTNRanking1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNRanking1ActionPerformed
        Ranking ra = new Ranking();
        ra.setSize(720, 670);
        ra.setLocation(0, 0);

        JPDashboard.removeAll();
        JPDashboard.add(ra, BorderLayout.CENTER);
        JPDashboard.revalidate();
        JPDashboard.repaint();
    }//GEN-LAST:event_BTNRanking1ActionPerformed

    private void BTNMiniziseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNMiniziseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNMiniziseActionPerformed

    private void BTNCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCloseActionPerformed

    }//GEN-LAST:event_BTNCloseActionPerformed

    private void BTNCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNCloseMouseClicked
        if (evt.getButton() == java.awt.event.MouseEvent.BUTTON1) {
            System.exit(0);
        }
    }//GEN-LAST:event_BTNCloseMouseClicked

    private void BTNMiniziseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNMiniziseMouseClicked
        if (evt.getButton() == java.awt.event.MouseEvent.BUTTON1) {
            this.setExtendedState(ICONIFIED);
        }
    }//GEN-LAST:event_BTNMiniziseMouseClicked

    private void JPEncMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPEncMousePressed
        if (evt.getButton() == java.awt.event.MouseEvent.BUTTON1) {
            LayoutX = evt.getX();
            LayoutY = evt.getY();/*Obtiene la posicion x,y*/
        }
    }//GEN-LAST:event_JPEncMousePressed

    private void JPEncMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPEncMouseDragged
        this.setLocation(evt.getXOnScreen() - LayoutX, evt.getYOnScreen() - LayoutY);
    }//GEN-LAST:event_JPEncMouseDragged

    private void BTNCerrarrSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCerrarrSesionActionPerformed
        this.dispose();
        Login il = new Login();
        il.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_BTNCerrarrSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNAbout;
    private javax.swing.JButton BTNCerrarrSesion;
    private javax.swing.JButton BTNClose;
    private javax.swing.JButton BTNInicio;
    private javax.swing.JButton BTNMinizise;
    private javax.swing.JButton BTNPreguntas;
    private javax.swing.JButton BTNRanking1;
    private javax.swing.JPanel JPBar;
    private javax.swing.JPanel JPDashboard;
    private javax.swing.JPanel JPEnc;
    private javax.swing.JLabel LBIcon;
    private javax.swing.JLabel LBImTop1;
    private javax.swing.JLabel LBImgAbout;
    private javax.swing.JLabel LBImgInicio;
    private javax.swing.JLabel LBImgLogOut;
    private javax.swing.JLabel LBImgPregunta1;
    private javax.swing.JLabel TXTImgUsu;
    public javax.swing.JLabel TXTNomUsu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
