package Vista;

import Modelo.Conexion;
import Modelo.Hash;
import Modelo.SQLUsuarios;
import Modelo.Usuarios;
import Controlador.Operaciones;
import com.toedter.calendar.JDateChooser;
import java.awt.BorderLayout;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author KevinJp
 */
public class Registro extends javax.swing.JFrame {

    CorreoExiste ce = new CorreoExiste();
    /**
     * Creates new form InicioLogin
     *
     */
    Conexion cx = new Conexion();

    int LayoutX;
    int LayoutY;
    ValNombre vn = new ValNombre();
    ValCorreo vc = new ValCorreo();
    ValApellido va = new ValApellido();
    ValContraseña vco = new ValContraseña();
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPDashboard = new javax.swing.JPanel();
        JPContenedor1 = new javax.swing.JPanel();
        TXTLogin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BTNLogin = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        JPContenedor2 = new javax.swing.JPanel();
        LBNombre = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        LBApellido = new javax.swing.JLabel();
        TXTNombre = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        LBContraseña = new javax.swing.JLabel();
        TXTApellido = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        LBConfirmarContraseña = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        LBFecha = new javax.swing.JLabel();
        TXTCorreo = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        LBNombre2 = new javax.swing.JLabel();
        DFechaNac = new com.toedter.calendar.JDateChooser();
        jSeparator12 = new javax.swing.JSeparator();
        BTNRegistro = new javax.swing.JButton();
        TXTContraseña = new javax.swing.JPasswordField();
        TXTConfirmarContraseña = new javax.swing.JPasswordField();
        JPCorreoExiste = new javax.swing.JPanel();
        JPEnc = new javax.swing.JPanel();
        BTNMinizise = new javax.swing.JButton();
        BTNClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        LBIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        JPDashboard.setBackground(new java.awt.Color(2, 0, 8));
        JPDashboard.setPreferredSize(new java.awt.Dimension(1020, 650));

        JPContenedor1.setBackground(new java.awt.Color(2, 0, 8));

        TXTLogin.setBackground(new java.awt.Color(4, 0, 14));
        TXTLogin.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        TXTLogin.setForeground(new java.awt.Color(255, 255, 255));
        TXTLogin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TXTLogin.setText("Registrate");
        TXTLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("¿Ya tienes cuenta?");

        BTNLogin.setBackground(new java.awt.Color(2, 0, 8));
        BTNLogin.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        BTNLogin.setForeground(new java.awt.Color(255, 255, 255));
        BTNLogin.setText("Iniciar sesión");
        BTNLogin.setBorder(null);
        BTNLogin.setBorderPainted(false);
        BTNLogin.setContentAreaFilled(false);
        BTNLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTNLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNLoginActionPerformed(evt);
            }
        });

        jSeparator5.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));

        JPContenedor2.setBackground(new java.awt.Color(2, 0, 8));

        LBNombre.setBackground(new java.awt.Color(4, 0, 14));
        LBNombre.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        LBNombre.setForeground(new java.awt.Color(255, 255, 255));
        LBNombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBNombre.setText("Correo");
        LBNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jSeparator6.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator7.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);

        LBApellido.setBackground(new java.awt.Color(4, 0, 14));
        LBApellido.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        LBApellido.setForeground(new java.awt.Color(255, 255, 255));
        LBApellido.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBApellido.setText("Apellido");
        LBApellido.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        TXTNombre.setBackground(new java.awt.Color(2, 0, 8));
        TXTNombre.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        TXTNombre.setForeground(new java.awt.Color(255, 255, 255));
        TXTNombre.setToolTipText("");
        TXTNombre.setBorder(null);
        TXTNombre.setCaretColor(new java.awt.Color(255, 255, 255));
        TXTNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TXTNombre.setDragEnabled(true);
        TXTNombre.setOpaque(true);
        TXTNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TXTNombreMouseClicked(evt);
            }
        });
        TXTNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTNombreActionPerformed(evt);
            }
        });
        TXTNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTNombreKeyTyped(evt);
            }
        });

        jSeparator8.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));

        LBContraseña.setBackground(new java.awt.Color(4, 0, 14));
        LBContraseña.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        LBContraseña.setForeground(new java.awt.Color(255, 255, 255));
        LBContraseña.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBContraseña.setText("Contraseña");
        LBContraseña.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        TXTApellido.setBackground(new java.awt.Color(2, 0, 8));
        TXTApellido.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        TXTApellido.setForeground(new java.awt.Color(255, 255, 255));
        TXTApellido.setToolTipText("");
        TXTApellido.setBorder(null);
        TXTApellido.setCaretColor(new java.awt.Color(255, 255, 255));
        TXTApellido.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TXTApellido.setDragEnabled(true);
        TXTApellido.setOpaque(true);
        TXTApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TXTApellidoMouseClicked(evt);
            }
        });
        TXTApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTApellidoActionPerformed(evt);
            }
        });
        TXTApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTApellidoKeyTyped(evt);
            }
        });

        jSeparator9.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator9.setForeground(new java.awt.Color(255, 255, 255));

        LBConfirmarContraseña.setBackground(new java.awt.Color(4, 0, 14));
        LBConfirmarContraseña.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        LBConfirmarContraseña.setForeground(new java.awt.Color(255, 255, 255));
        LBConfirmarContraseña.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBConfirmarContraseña.setText("Confirmar contraseña");
        LBConfirmarContraseña.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jSeparator10.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator10.setForeground(new java.awt.Color(255, 255, 255));

        LBFecha.setBackground(new java.awt.Color(4, 0, 14));
        LBFecha.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        LBFecha.setForeground(new java.awt.Color(255, 255, 255));
        LBFecha.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBFecha.setText("Fecha de nacimiento");
        LBFecha.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        TXTCorreo.setBackground(new java.awt.Color(2, 0, 8));
        TXTCorreo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        TXTCorreo.setForeground(new java.awt.Color(255, 255, 255));
        TXTCorreo.setToolTipText("");
        TXTCorreo.setBorder(null);
        TXTCorreo.setCaretColor(new java.awt.Color(255, 255, 255));
        TXTCorreo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TXTCorreo.setDragEnabled(true);
        TXTCorreo.setOpaque(true);
        TXTCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TXTCorreoMouseClicked(evt);
            }
        });
        TXTCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTCorreoActionPerformed(evt);
            }
        });

        jSeparator11.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator11.setForeground(new java.awt.Color(255, 255, 255));

        LBNombre2.setBackground(new java.awt.Color(4, 0, 14));
        LBNombre2.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        LBNombre2.setForeground(new java.awt.Color(255, 255, 255));
        LBNombre2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBNombre2.setText("Nombre");
        LBNombre2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        DFechaNac.setBackground(new java.awt.Color(0, 0, 0));
        DFechaNac.setForeground(new java.awt.Color(204, 204, 204));
        DFechaNac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DFechaNacMouseClicked(evt);
            }
        });

        jSeparator12.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator12.setForeground(new java.awt.Color(255, 255, 255));

        BTNRegistro.setBackground(new java.awt.Color(2, 0, 8));
        BTNRegistro.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        BTNRegistro.setForeground(new java.awt.Color(255, 255, 255));
        BTNRegistro.setText("Registrarse");
        BTNRegistro.setBorder(null);
        BTNRegistro.setBorderPainted(false);
        BTNRegistro.setContentAreaFilled(false);
        BTNRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTNRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTNRegistroMouseClicked(evt);
            }
        });
        BTNRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNRegistroActionPerformed(evt);
            }
        });

        TXTContraseña.setBackground(new java.awt.Color(2, 0, 8));
        TXTContraseña.setFont(new java.awt.Font("Roboto", 0, 30)); // NOI18N
        TXTContraseña.setForeground(new java.awt.Color(255, 255, 255));
        TXTContraseña.setBorder(null);
        TXTContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TXTContraseñaMouseClicked(evt);
            }
        });

        TXTConfirmarContraseña.setBackground(new java.awt.Color(2, 0, 8));
        TXTConfirmarContraseña.setFont(new java.awt.Font("Roboto", 0, 30)); // NOI18N
        TXTConfirmarContraseña.setForeground(new java.awt.Color(255, 255, 255));
        TXTConfirmarContraseña.setBorder(null);
        TXTConfirmarContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TXTConfirmarContraseñaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JPContenedor2Layout = new javax.swing.GroupLayout(JPContenedor2);
        JPContenedor2.setLayout(JPContenedor2Layout);
        JPContenedor2Layout.setHorizontalGroup(
            JPContenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPContenedor2Layout.createSequentialGroup()
                .addGroup(JPContenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPContenedor2Layout.createSequentialGroup()
                        .addGroup(JPContenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPContenedor2Layout.createSequentialGroup()
                                .addGap(210, 210, 210)
                                .addGroup(JPContenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LBNombre2)
                                    .addComponent(LBFecha)
                                    .addComponent(LBNombre))
                                .addGap(112, 112, 112))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPContenedor2Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(JPContenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXTCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(102, 102, 102)))
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(JPContenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPContenedor2Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(JPContenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LBContraseña)
                                    .addComponent(LBApellido)
                                    .addComponent(LBConfirmarContraseña)))
                            .addGroup(JPContenedor2Layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(TXTApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPContenedor2Layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addGroup(JPContenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXTContraseña, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXTConfirmarContraseña, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(JPContenedor2Layout.createSequentialGroup()
                        .addGap(414, 414, 414)
                        .addComponent(BTNRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(207, Short.MAX_VALUE))
        );
        JPContenedor2Layout.setVerticalGroup(
            JPContenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPContenedor2Layout.createSequentialGroup()
                .addGroup(JPContenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPContenedor2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(LBNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TXTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LBFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(LBNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TXTCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPContenedor2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(LBApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TXTApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(LBContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TXTContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LBConfirmarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TXTConfirmarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JPContenedor1Layout = new javax.swing.GroupLayout(JPContenedor1);
        JPContenedor1.setLayout(JPContenedor1Layout);
        JPContenedor1Layout.setHorizontalGroup(
            JPContenedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPContenedor2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JPContenedor1Layout.createSequentialGroup()
                .addGap(460, 460, 460)
                .addComponent(TXTLogin)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPContenedor1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPContenedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(446, 446, 446))
        );
        JPContenedor1Layout.setVerticalGroup(
            JPContenedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPContenedor1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(TXTLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPContenedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(BTNLogin))
                .addGap(0, 0, 0)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JPContenedor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        JPCorreoExiste.setBackground(new java.awt.Color(2, 0, 8));

        javax.swing.GroupLayout JPCorreoExisteLayout = new javax.swing.GroupLayout(JPCorreoExiste);
        JPCorreoExiste.setLayout(JPCorreoExisteLayout);
        JPCorreoExisteLayout.setHorizontalGroup(
            JPCorreoExisteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        JPCorreoExisteLayout.setVerticalGroup(
            JPCorreoExisteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout JPDashboardLayout = new javax.swing.GroupLayout(JPDashboard);
        JPDashboard.setLayout(JPDashboardLayout);
        JPDashboardLayout.setHorizontalGroup(
            JPDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPDashboardLayout.createSequentialGroup()
                .addGap(399, 399, 399)
                .addComponent(JPCorreoExiste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(390, Short.MAX_VALUE))
            .addGroup(JPDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(JPContenedor1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPDashboardLayout.setVerticalGroup(
            JPDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPDashboardLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(JPCorreoExiste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPDashboardLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JPContenedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        JPEnc.setBackground(new java.awt.Color(2, 0, 8));
        JPEnc.setPreferredSize(new java.awt.Dimension(1020, 40));
        JPEnc.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                JPEncMouseDragged(evt);
            }
        });
        JPEnc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPEncMousePressed(evt);
            }
        });

        BTNMinizise.setBackground(new java.awt.Color(2, 0, 8));
        BTNMinizise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minimize.png"))); // NOI18N
        BTNMinizise.setBorder(null);
        BTNMinizise.setBorderPainted(false);
        BTNMinizise.setContentAreaFilled(false);
        BTNMinizise.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTNMinizise.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BTNMinizise.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BTNMinizise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTNMiniziseMouseClicked(evt);
            }
        });
        BTNMinizise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNMiniziseActionPerformed(evt);
            }
        });

        BTNClose.setBackground(new java.awt.Color(2, 0, 8));
        BTNClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/close.png"))); // NOI18N
        BTNClose.setBorder(null);
        BTNClose.setBorderPainted(false);
        BTNClose.setContentAreaFilled(false);
        BTNClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTNClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTNCloseMouseClicked(evt);
            }
        });
        BTNClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCloseActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("EcoCal");

        LBIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/huella-de-carbono icon.png"))); // NOI18N

        javax.swing.GroupLayout JPEncLayout = new javax.swing.GroupLayout(JPEnc);
        JPEnc.setLayout(JPEncLayout);
        JPEncLayout.setHorizontalGroup(
            JPEncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPEncLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LBIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BTNMinizise, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BTNClose, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        JPEncLayout.setVerticalGroup(
            JPEncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LBIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JPEncLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPEncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNClose, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNMinizise, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPEnc, javax.swing.GroupLayout.DEFAULT_SIZE, 1119, Short.MAX_VALUE)
            .addComponent(JPDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 1119, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(JPEnc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(JPDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTNMiniziseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNMiniziseMouseClicked
        if (evt.getButton() == java.awt.event.MouseEvent.BUTTON1) {
            this.setExtendedState(ICONIFIED);
        }
    }//GEN-LAST:event_BTNMiniziseMouseClicked

    private void BTNMiniziseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNMiniziseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNMiniziseActionPerformed

    private void BTNCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNCloseMouseClicked
        if (evt.getButton() == java.awt.event.MouseEvent.BUTTON1) {
            System.exit(0);
        }
    }//GEN-LAST:event_BTNCloseMouseClicked

    private void BTNCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCloseActionPerformed

    }//GEN-LAST:event_BTNCloseActionPerformed

    private void JPEncMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPEncMouseDragged
        this.setLocation(evt.getXOnScreen() - LayoutX, evt.getYOnScreen() - LayoutY);
    }//GEN-LAST:event_JPEncMouseDragged

    private void JPEncMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPEncMousePressed
        if (evt.getButton() == java.awt.event.MouseEvent.BUTTON1) {
            LayoutX = evt.getX();
            LayoutY = evt.getY();/*Obtiene la posicion x,y*/
        }
    }//GEN-LAST:event_JPEncMousePressed

    private void BTNLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNLoginActionPerformed
        Login lg = new Login();
        
        this.dispose();
        lg.setVisible(true);
    }//GEN-LAST:event_BTNLoginActionPerformed

    private void TXTNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTNombreActionPerformed

    private void TXTNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTNombreKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c < ' ' || c > ' '))
            evt.consume();
    }//GEN-LAST:event_TXTNombreKeyTyped

    private void TXTApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTApellidoActionPerformed

    private void TXTApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTApellidoKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c < ' ' || c > ' '))
            evt.consume();
    }//GEN-LAST:event_TXTApellidoKeyTyped

    private void TXTCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTCorreoActionPerformed

    private void BTNRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNRegistroActionPerformed
        SQLUsuarios sqlus = new SQLUsuarios();
        Usuarios us = new Usuarios();
        Operaciones validaciones = new Operaciones();
        us.setNombre(TXTNombre.getText());
        us.setApellido(TXTApellido.getText());
        us.setCorreo(TXTCorreo.getText());;
        us.setContraseña(String.valueOf(TXTContraseña.getPassword()));
        String confirmar_contraseña = String.valueOf(TXTConfirmarContraseña.getPassword());
        us.setFechaNac(DFechaNac);

        if (!validaciones.Estexto(us.getNombre().toUpperCase().trim()) || us.getNombre().trim().isEmpty()) {
            vn.setSize(330, 52);
                                    vn.setLocation(0, 0);

                                    JPCorreoExiste.removeAll();
                                    JPCorreoExiste.add(vn, BorderLayout.CENTER);
                                    JPCorreoExiste.revalidate();
                                    JPCorreoExiste.repaint();
                                    vn.setVisible(true);
         
        } else {
            if (!validaciones.Estexto(us.getApellido().toUpperCase().trim()) || us.getApellido().trim().isEmpty()) {
               va.setSize(330, 52);
                                    va.setLocation(0, 0);

                                    JPCorreoExiste.removeAll();
                                    JPCorreoExiste.add(va, BorderLayout.CENTER);
                                    JPCorreoExiste.revalidate();
                                    JPCorreoExiste.repaint();
                                    va.setVisible(true);
            } else {
                if (!validaciones.EsCorreo(us.getCorreo())) {
                   vc.setSize(330, 52);
                                    vc.setLocation(0, 0);

                                    JPCorreoExiste.removeAll();
                                    JPCorreoExiste.add(vc, BorderLayout.CENTER);
                                    JPCorreoExiste.revalidate();
                                    JPCorreoExiste.repaint();
                                    vc.setVisible(true);
                } else {
                    if (!validaciones.EsContrasena(us.getContraseña())) {
                        JOptionPane.showMessageDialog(null, "No es una contraseña valida, deberia de contener lo siguiente:\n - Por lo menos 8 caracteres\n - Por lo menos un Numero\n - Por lo menos una letra Mayuscula y una letra Minuscula\n - No debe de contener espacios", "Validación de datos", JOptionPane.ERROR_MESSAGE);
                    } else {
                        if (!us.getContraseña().equals(confirmar_contraseña)) {
                           vco.setSize(330, 52);
                                    vco.setLocation(0, 0);

                                    JPCorreoExiste.removeAll();
                                    JPCorreoExiste.add(vco, BorderLayout.CENTER);
                                    JPCorreoExiste.revalidate();
                                    JPCorreoExiste.repaint();
                                    vco.setVisible(true);
                        } else {
                            if(DFechaNac.getDate()==null){
                                JOptionPane.showMessageDialog(null, "Ingrese su fecha de nacimiento", "Validación de datos", JOptionPane.ERROR_MESSAGE);
                            }else{
                            Hash hash = new Hash();
                            String nuevoPass = hash.sha1(us.getContraseña());
                            String respuesta = sqlus.registrar(us);
                            switch (respuesta) {
                                case "existe":

                                    ce.setSize(257, 52);
                                    ce.setLocation(0, 0);

                                    JPCorreoExiste.removeAll();
                                    JPCorreoExiste.add(ce, BorderLayout.CENTER);
                                    JPCorreoExiste.revalidate();
                                    JPCorreoExiste.repaint();
                                    ce.setVisible(true);
                                    break;

                                case "registrado":
                                    this.dispose();
                                    Login lg = new Login();
                                    lg.setVisible(true);
                                    break;

                                default:
                                    JOptionPane.showMessageDialog(null, "Ocurrio un error");
                                    break;
                            }
                        }
                    }
                }
            }
        }
        }
    }//GEN-LAST:event_BTNRegistroActionPerformed

    private void BTNRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNRegistroMouseClicked
        
    }//GEN-LAST:event_BTNRegistroMouseClicked

    private void TXTCorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTCorreoMouseClicked
        ce.setVisible(false);
        vc.setVisible(false);
    }//GEN-LAST:event_TXTCorreoMouseClicked

    private void DFechaNacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DFechaNacMouseClicked
        
    }//GEN-LAST:event_DFechaNacMouseClicked

    private void TXTNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTNombreMouseClicked
        vn.setVisible(false);
    }//GEN-LAST:event_TXTNombreMouseClicked

    private void TXTApellidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTApellidoMouseClicked
        va.setVisible(false);
    }//GEN-LAST:event_TXTApellidoMouseClicked

    private void TXTContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTContraseñaMouseClicked
        vco.setVisible(false);
    }//GEN-LAST:event_TXTContraseñaMouseClicked

    private void TXTConfirmarContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTConfirmarContraseñaMouseClicked
        vco.setVisible(false);
    }//GEN-LAST:event_TXTConfirmarContraseñaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNClose;
    private javax.swing.JButton BTNLogin;
    private javax.swing.JButton BTNMinizise;
    private javax.swing.JButton BTNRegistro;
    private com.toedter.calendar.JDateChooser DFechaNac;
    private javax.swing.JPanel JPContenedor1;
    private javax.swing.JPanel JPContenedor2;
    private javax.swing.JPanel JPCorreoExiste;
    private javax.swing.JPanel JPDashboard;
    private javax.swing.JPanel JPEnc;
    private javax.swing.JLabel LBApellido;
    private javax.swing.JLabel LBConfirmarContraseña;
    private javax.swing.JLabel LBContraseña;
    private javax.swing.JLabel LBFecha;
    private javax.swing.JLabel LBIcon;
    private javax.swing.JLabel LBNombre;
    private javax.swing.JLabel LBNombre2;
    private javax.swing.JTextField TXTApellido;
    private javax.swing.JPasswordField TXTConfirmarContraseña;
    private javax.swing.JPasswordField TXTContraseña;
    private javax.swing.JTextField TXTCorreo;
    private javax.swing.JLabel TXTLogin;
    private javax.swing.JTextField TXTNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
