package Vista;

import java.sql.*;
import Controlador.RescuperacionPassword;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.util.Properties;
import javax.mail.*;
import javax.mail.internet.*;
import javax.swing.JOptionPane;

/**
 *
 * @author pinku
 */
public class ResetPass extends javax.swing.JFrame {

    /**
     * Creates new form ResetPass
     */
    String contraseña;
    String correo;

    public ResetPass() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    final void EnviarCorreo() {
        RescuperacionPassword recu = new RescuperacionPassword();
        recu.correo = TXTCorreo.getText();
        String correoRemitente = "soporte.ecocal@gmail.com";
        String passRemitente = "xuwntiqucumtoukk";

        try {
            ResultSet rs = recu.RecuperacionContra();
            while (rs.next()) {
                correo = rs.getString("Correo");
                contraseña = rs.getString("Contraseña");
            }
        } catch (Exception e) {
            System.out.println("Error al capturar datos");
        }

        Properties props = System.getProperties();
        Session session = Session.getDefaultInstance(props);
        props.put("mail.smtp.ssl.trust", "smtp.gmail.com"); // El servidor SMTP de Google
        props.put("mail.smtp.port", "587"); // Puerto SMTP seguro de Google
        props.put("mail.smtp.auth", "true"); // Autenticación mediante usuario y pass
        props.put("mail.smtp.ssl.protocols", "TLSv1.2");
        session.getProperties().put("mail.smtp.starttls.enable", "true"); // Conexió segura al servidor
        props.put("mail.smtp.user", correoRemitente);
        props.put("mail.smtp.clave", passRemitente);

        
        String correoReceptor = correo;
        String asunto = "Recuperacion Contraseña";
        String mensaje = "Tu contraseña es: " + contraseña;

        MimeMessage msg = new MimeMessage(session);
        try {
            msg.setFrom(new InternetAddress(correoRemitente));
            msg.addRecipients(Message.RecipientType.TO, correoReceptor);
            msg.setSubject(asunto);
            msg.setText(mensaje);
            Transport transport = session.getTransport("smtp");
            transport.connect("smtp.gmail.com", correoRemitente, passRemitente);
            transport.sendMessage(msg, msg.getAllRecipients());
            transport.close();
            JOptionPane.showMessageDialog(this, "Correo enviado");

        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPRecuperar = new javax.swing.JPanel();
        LBRestablecerPass = new javax.swing.JLabel();
        TXTCorreo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BTNCancelar = new javax.swing.JButton();
        BTNEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        JPRecuperar.setBackground(new java.awt.Color(2, 0, 8));

        LBRestablecerPass.setBackground(new java.awt.Color(4, 0, 14));
        LBRestablecerPass.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        LBRestablecerPass.setForeground(new java.awt.Color(204, 204, 204));
        LBRestablecerPass.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBRestablecerPass.setText("Restablecer tu contraseña");
        LBRestablecerPass.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        TXTCorreo.setBackground(new java.awt.Color(2, 0, 8));
        TXTCorreo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        TXTCorreo.setForeground(new java.awt.Color(255, 255, 255));
        TXTCorreo.setToolTipText("");
        TXTCorreo.setBorder(null);
        TXTCorreo.setCaretColor(new java.awt.Color(255, 255, 255));
        TXTCorreo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TXTCorreo.setDragEnabled(true);
        TXTCorreo.setOpaque(true);
        TXTCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TXTCorreoMouseClicked(evt);
            }
        });
        TXTCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTCorreoActionPerformed(evt);
            }
        });
        TXTCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TXTCorreoKeyPressed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Ingresa tu correo de EcoCal y te enviaremos un e-mail ");

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("para  que puedas restablecer u contraseña");

        BTNCancelar.setBackground(new java.awt.Color(2, 0, 8));
        BTNCancelar.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        BTNCancelar.setForeground(new java.awt.Color(204, 204, 204));
        BTNCancelar.setText("Cancelar");
        BTNCancelar.setBorder(null);
        BTNCancelar.setBorderPainted(false);
        BTNCancelar.setContentAreaFilled(false);
        BTNCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTNCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCancelarActionPerformed(evt);
            }
        });

        BTNEnviar.setBackground(new java.awt.Color(2, 0, 8));
        BTNEnviar.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        BTNEnviar.setForeground(new java.awt.Color(204, 204, 204));
        BTNEnviar.setText("Enviar");
        BTNEnviar.setBorder(null);
        BTNEnviar.setBorderPainted(false);
        BTNEnviar.setContentAreaFilled(false);
        BTNEnviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTNEnviar.setFocusable(false);
        BTNEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPRecuperarLayout = new javax.swing.GroupLayout(JPRecuperar);
        JPRecuperar.setLayout(JPRecuperarLayout);
        JPRecuperarLayout.setHorizontalGroup(
            JPRecuperarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPRecuperarLayout.createSequentialGroup()
                .addGroup(JPRecuperarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPRecuperarLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(JPRecuperarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(LBRestablecerPass)
                            .addComponent(jLabel2)))
                    .addGroup(JPRecuperarLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(JPRecuperarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(JPRecuperarLayout.createSequentialGroup()
                                .addComponent(BTNEnviar)
                                .addGap(56, 56, 56)
                                .addComponent(BTNCancelar)
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JPRecuperarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TXTCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        JPRecuperarLayout.setVerticalGroup(
            JPRecuperarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPRecuperarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(LBRestablecerPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(25, 25, 25)
                .addComponent(TXTCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(JPRecuperarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNEnviar)
                    .addComponent(BTNCancelar))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPRecuperar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPRecuperar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TXTCorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTCorreoMouseClicked

    }//GEN-LAST:event_TXTCorreoMouseClicked

    private void TXTCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTCorreoActionPerformed

    private void TXTCorreoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTCorreoKeyPressed

    }//GEN-LAST:event_TXTCorreoKeyPressed

    private void BTNCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_BTNCancelarActionPerformed

    private void BTNEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEnviarActionPerformed
        EnviarCorreo();
        this.dispose();
    }//GEN-LAST:event_BTNEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResetPass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCancelar;
    private javax.swing.JButton BTNEnviar;
    private javax.swing.JPanel JPRecuperar;
    private javax.swing.JLabel LBRestablecerPass;
    private javax.swing.JTextField TXTCorreo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
